package html

type traits uint16

const (
	normalTag traits = 1 << iota
	rawTag
	nonPhrasingTag
	objectTag
	omitPTag // omit p end tag if it is followed by this start tag
	keepPTag // keep p end tag if it is followed by this end tag
)

const (
	booleanAttr traits = 1 << iota
	caselessAttr
	urlAttr
	trimAttr
)

var tagMap = map[Hash]traits{
	A:          keepPTag,
	Abbr:       normalTag,
	Address:    nonPhrasingTag | omitPTag,
	Area:       normalTag,
	Article:    nonPhrasingTag | omitPTag,
	Aside:      nonPhrasingTag | omitPTag,
	Audio:      objectTag | keepPTag,
	B:          normalTag,
	Base:       normalTag,
	Bb:         normalTag,
	Bdi:        normalTag,
	Bdo:        normalTag,
	Blockquote: nonPhrasingTag | omitPTag,
	Body:       nonPhrasingTag,
	Br:         nonPhrasingTag,
	Button:     objectTag,
	Canvas:     objectTag,
	Caption:    nonPhrasingTag,
	Cite:       normalTag,
	Code:       normalTag,
	Col:        nonPhrasingTag,
	Colgroup:   nonPhrasingTag,
	Data:       normalTag,
	Datalist:   normalTag,
	Dd:         nonPhrasingTag,
	Del:        keepPTag,
	Details:    omitPTag,
	Dfn:        normalTag,
	Dialog:     normalTag,
	Div:        nonPhrasingTag | omitPTag,
	Dl:         nonPhrasingTag | omitPTag,
	Dt:         nonPhrasingTag,
	Em:         normalTag,
	Embed:      nonPhrasingTag,
	Fieldset:   nonPhrasingTag | omitPTag,
	Figcaption: nonPhrasingTag | omitPTag,
	Figure:     nonPhrasingTag | omitPTag,
	Footer:     nonPhrasingTag | omitPTag,
	Form:       nonPhrasingTag | omitPTag,
	H1:         nonPhrasingTag | omitPTag,
	H2:         nonPhrasingTag | omitPTag,
	H3:         nonPhrasingTag | omitPTag,
	H4:         nonPhrasingTag | omitPTag,
	H5:         nonPhrasingTag | omitPTag,
	H6:         nonPhrasingTag | omitPTag,
	Head:       nonPhrasingTag,
	Header:     nonPhrasingTag | omitPTag,
	Hgroup:     nonPhrasingTag,
	Hr:         nonPhrasingTag | omitPTag,
	Html:       nonPhrasingTag,
	I:          normalTag,
	Iframe:     rawTag | objectTag,
	Img:        objectTag,
	Input:      objectTag,
	Ins:        keepPTag,
	Kbd:        normalTag,
	Label:      normalTag,
	Legend:     normalTag,
	Li:         nonPhrasingTag,
	Link:       normalTag,
	Main:       nonPhrasingTag | omitPTag,
	Map:        keepPTag,
	Mark:       normalTag,
	Math:       rawTag,
	Menu:       omitPTag,
	Meta:       nonPhrasingTag,
	Meter:      objectTag,
	Nav:        nonPhrasingTag | omitPTag,
	Noscript:   nonPhrasingTag | keepPTag,
	Object:     objectTag,
	Ol:         nonPhrasingTag | omitPTag,
	Optgroup:   normalTag,
	Option:     normalTag,
	Output:     nonPhrasingTag,
	P:          nonPhrasingTag | omitPTag,
	Param:      normalTag,
	Picture:    objectTag,
	Pre:        nonPhrasingTag | omitPTag,
	Progress:   objectTag,
	Q:          objectTag,
	Rp:         normalTag,
	Rt:         normalTag,
	Ruby:       normalTag,
	S:          normalTag,
	Samp:       normalTag,
	Script:     rawTag,
	Section:    nonPhrasingTag | omitPTag,
	Select:     objectTag,
	Slot:       normalTag,
	Small:      normalTag,
	Source:     normalTag,
	Span:       normalTag,
	Strong:     normalTag,
	Style:      rawTag | nonPhrasingTag,
	Sub:        normalTag,
	Summary:    normalTag,
	Sup:        normalTag,
	Svg:        rawTag | objectTag,
	Table:      nonPhrasingTag | omitPTag,
	Tbody:      nonPhrasingTag,
	Td:         nonPhrasingTag,
	Template:   normalTag,
	Textarea:   rawTag | objectTag,
	Tfoot:      nonPhrasingTag,
	Th:         nonPhrasingTag,
	Thead:      nonPhrasingTag,
	Time:       normalTag,
	Title:      nonPhrasingTag,
	Tr:         nonPhrasingTag,
	Track:      normalTag,
	U:          normalTag,
	Ul:         nonPhrasingTag | omitPTag,
	Var:        normalTag,
	Video:      objectTag | keepPTag,
	Wbr:        normalTag,
}

var attrMap = map[Hash]traits{
	Accept:          caselessAttr,
	Accept_Charset:  caselessAttr,
	Action:          urlAttr,
	Align:           caselessAttr,
	Alink:           caselessAttr,
	Allowfullscreen: booleanAttr,
	Async:           booleanAttr,
	Autofocus:       booleanAttr,
	Autoplay:        booleanAttr,
	Axis:            caselessAttr,
	Background:      urlAttr,
	Bgcolor:         caselessAttr,
	Charset:         caselessAttr,
	Checked:         booleanAttr,
	Cite:            urlAttr,
	Class:           trimAttr,
	Classid:         urlAttr,
	Clear:           caselessAttr,
	Codebase:        urlAttr,
	Codetype:        caselessAttr,
	Color:           caselessAttr,
	Cols:            trimAttr,
	Colspan:         trimAttr,
	Compact:         booleanAttr,
	Controls:        booleanAttr,
	Data:            urlAttr,
	Declare:         booleanAttr,
	Default:         booleanAttr,
	DefaultChecked:  booleanAttr,
	DefaultMuted:    booleanAttr,
	DefaultSelected: booleanAttr,
	Defer:           booleanAttr,
	Dir:             caselessAttr,
	Disabled:        booleanAttr,
	Enabled:         booleanAttr,
	Enctype:         caselessAttr,
	Face:            caselessAttr,
	Formaction:      urlAttr,
	Formnovalidate:  booleanAttr,
	Frame:           caselessAttr,
	Hidden:          booleanAttr,
	Href:            urlAttr,
	Hreflang:        caselessAttr,
	Http_Equiv:      caselessAttr,
	Icon:            urlAttr,
	Inert:           booleanAttr,
	Ismap:           booleanAttr,
	Itemscope:       booleanAttr,
	Lang:            caselessAttr,
	Language:        caselessAttr,
	Link:            caselessAttr,
	Longdesc:        urlAttr,
	Manifest:        urlAttr,
	Maxlength:       trimAttr,
	Media:           caselessAttr | trimAttr,
	Method:          caselessAttr,
	Multiple:        booleanAttr,
	Muted:           booleanAttr,
	Nohref:          booleanAttr,
	Noresize:        booleanAttr,
	Noshade:         booleanAttr,
	Novalidate:      booleanAttr,
	Nowrap:          booleanAttr,
	Open:            booleanAttr,
	Pauseonexit:     booleanAttr,
	Poster:          urlAttr,
	Profile:         urlAttr,
	Readonly:        booleanAttr,
	Rel:             caselessAttr,
	Required:        booleanAttr,
	Rev:             caselessAttr,
	Reversed:        booleanAttr,
	Rows:            trimAttr,
	Rowspan:         trimAttr,
	Rules:           caselessAttr,
	Scope:           caselessAttr,
	Scoped:          booleanAttr,
	Scrolling:       caselessAttr,
	Seamless:        booleanAttr,
	Selected:        booleanAttr,
	Shape:           caselessAttr,
	Size:            trimAttr,
	Sortable:        booleanAttr,
	Span:            trimAttr,
	Src:             urlAttr,
	Srcset:          trimAttr,
	Tabindex:        trimAttr,
	Target:          caselessAttr,
	Text:            caselessAttr,
	Translate:       booleanAttr,
	Truespeed:       booleanAttr,
	Type:            caselessAttr,
	Typemustmatch:   booleanAttr,
	Undeterminate:   booleanAttr,
	Usemap:          urlAttr,
	Valign:          caselessAttr,
	Valuetype:       caselessAttr,
	Vlink:           caselessAttr,
	Visible:         booleanAttr,
	Xmlns:           urlAttr,
}

var jsMimetypes = map[string]bool{
	"text/javascript":        true,
	"application/javascript": true,
}
