package html // import "github.com/tdewolff/minify/html"

import "github.com/tdewolff/parse/html"

var rawTagMap = map[html.Hash]bool{
	html.Code:     true,
	html.Iframe:   true,
	html.Math:     true,
	html.Pre:      true,
	html.Script:   true,
	html.Style:    true,
	html.Svg:      true,
	html.Textarea: true,
}

var nonPhrasingTagMap = map[html.Hash]bool{
	html.Address:    true,
	html.Article:    true,
	html.Aside:      true,
	html.Blockquote: true,
	html.Body:       true,
	html.Br:         true,
	html.Canvas:     true,
	html.Caption:    true,
	html.Col:        true,
	html.Colgroup:   true,
	html.Dd:         true,
	html.Div:        true,
	html.Dl:         true,
	html.Dt:         true,
	html.Embed:      true,
	html.Fieldset:   true,
	html.Figcaption: true,
	html.Figure:     true,
	html.Footer:     true,
	html.Form:       true,
	html.H1:         true,
	html.H2:         true,
	html.H3:         true,
	html.H4:         true,
	html.H5:         true,
	html.H6:         true,
	html.Head:       true,
	html.Header:     true,
	html.Hgroup:     true,
	html.Hr:         true,
	html.Html:       true,
	html.Li:         true,
	html.Main:       true,
	html.Meta:       true,
	html.Nav:        true,
	html.Noscript:   true,
	html.Ol:         true,
	html.Output:     true,
	html.P:          true,
	html.Pre:        true,
	html.Progress:   true,
	html.Section:    true,
	html.Style:      true,
	html.Table:      true,
	html.Tbody:      true,
	html.Td:         true,
	html.Tfoot:      true,
	html.Th:         true,
	html.Thead:      true,
	html.Title:      true,
	html.Tr:         true,
	html.Ul:         true,
	html.Video:      true,
}

var booleanAttrMap = map[html.Hash]bool{
	html.Allowfullscreen: true,
	html.Async:           true,
	html.Autofocus:       true,
	html.Autoplay:        true,
	html.Checked:         true,
	html.Compact:         true,
	html.Controls:        true,
	html.Declare:         true,
	html.Default:         true,
	html.DefaultChecked:  true,
	html.DefaultMuted:    true,
	html.DefaultSelected: true,
	html.Defer:           true,
	html.Disabled:        true,
	html.Draggable:       true,
	html.Enabled:         true,
	html.Formnovalidate:  true,
	html.Hidden:          true,
	html.Inert:           true,
	html.Ismap:           true,
	html.Itemscope:       true,
	html.Multiple:        true,
	html.Muted:           true,
	html.Nohref:          true,
	html.Noresize:        true,
	html.Noshade:         true,
	html.Novalidate:      true,
	html.Nowrap:          true,
	html.Open:            true,
	html.Pauseonexit:     true,
	html.Readonly:        true,
	html.Required:        true,
	html.Reversed:        true,
	html.Scoped:          true,
	html.Seamless:        true,
	html.Selected:        true,
	html.Sortable:        true,
	html.Spellcheck:      true,
	html.Translate:       true,
	html.Truespeed:       true,
	html.Typemustmatch:   true,
	html.Undeterminate:   true,
	html.Visible:         true,
}

var caseInsensitiveAttrMap = map[html.Hash]bool{
	html.Accept:         true,
	html.Accept_Charset: true,
	html.Align:          true,
	html.Alink:          true,
	html.Axis:           true,
	html.Bgcolor:        true,
	html.Charset:        true,
	html.Clear:          true,
	html.Codetype:       true,
	html.Color:          true,
	html.Dir:            true,
	html.Enctype:        true,
	html.Face:           true,
	html.Frame:          true,
	html.Hreflang:       true,
	html.Http_Equiv:     true,
	html.Lang:           true,
	html.Language:       true,
	html.Link:           true,
	html.Media:          true,
	html.Method:         true,
	html.Rel:            true,
	html.Rev:            true,
	html.Rules:          true,
	html.Scope:          true,
	html.Scrolling:      true,
	html.Shape:          true,
	html.Target:         true,
	html.Text:           true,
	html.Type:           true,
	html.Valign:         true,
	html.Valuetype:      true,
	html.Vlink:          true,
}

var urlAttrMap = map[html.Hash]bool{
	html.Action:     true,
	html.Background: true,
	html.Cite:       true,
	html.Classid:    true,
	html.Codebase:   true,
	html.Data:       true,
	html.Formaction: true,
	html.Href:       true,
	html.Icon:       true,
	html.Longdesc:   true,
	html.Manifest:   true,
	html.Poster:     true,
	html.Profile:    true,
	html.Src:        true,
	html.Usemap:     true,
	html.Xmlns:      true,
}
